apiVersion: v1
kind: Pod
metadata:
  namespace: airflow
  name: mitre-heimdall-lite
  labels:
    app.kubernetes.io/name: mitre-heimdall-lite
spec:
  containers:
  - name: heimdall-lite
    image: 433429432064.dkr.ecr.eu-west-1.amazonaws.com/xac-repository/mitre-heimdall:2022-05-25
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        name: heimdall-svc
---
apiVersion: v1
kind: Service
metadata:
  namespace: airflow
  name: mitre-heimdall-lite
spec:
  selector:
    app.kubernetes.io/name: mitre-heimdall-lite
  ports:
  - protocol: TCP
    port: 80
    targetPort: heimdall-svc
